#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 18 15:58:33 MST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto acc4f1d0d16b4f6ba36771fb69b020d3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAB1B_behav xil_defaultlib.LAB1B -log elaborate.log"
xelab -wto acc4f1d0d16b4f6ba36771fb69b020d3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAB1B_behav xil_defaultlib.LAB1B -log elaborate.log

