#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Feb 19 05:57:58 MST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3ff2173c57f741f097a2dcff71bc6f7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Lab1B_tb_behav xil_defaultlib.Lab1B_tb -log elaborate.log"
xelab -wto 3ff2173c57f741f097a2dcff71bc6f7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Lab1B_tb_behav xil_defaultlib.Lab1B_tb -log elaborate.log

