set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {anode_7sd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cathode_7sd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports mux_out]

