#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Feb 05 00:17:08 MST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 93496de0b0c943a98e2d1ecbb19d2bca --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAB0B_tb_behav xil_defaultlib.LAB0B_tb -log elaborate.log"
xelab -wto 93496de0b0c943a98e2d1ecbb19d2bca --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAB0B_tb_behav xil_defaultlib.LAB0B_tb -log elaborate.log

